class Constants:
  NUM_STATES = 384
  NUM_ACTIONS = 5

  # Beaver
  BEAVER_STATE_INDEX_BEAVER_ENERGY = 0
  BEAVER_STATE_INDEX_MARSH_HEALTH = 1
  BEAVER_STATE_INDEX_LUMBER = 2
  BEAVER_STATE_INDEX_TREE = 3
  BEAVER_STATE_INDEX_MARSH = 4
  BEAVER_STATE_INDEX_WOLF = 5

  BEAVER_ACTION_INDEX_MOVE_TREE = 0
  BEAVER_ACTION_INDEX_MOVE_MARSH = 1
  BEAVER_ACTION_INDEX_EAT = 2
  BEAVER_ACTION_INDEX_PICK_UP_LUMBER = 3
  BEAVER_ACTION_INDEX_DROP_LUMBER = 4

  BEAVER_STATE_BEAVER_ENERGY_ZERO = "beaver energy zero"
  BEAVER_STATE_BEAVER_ENERGY_LOW = "beaver energy low"
  BEAVER_STATE_BEAVER_ENERGY_MED = "beaver energy med"
  BEAVER_STATE_BEAVER_ENERGY_HIGH = "beaver energy high"
  BEAVER_STATE_MARSH_HEALTH_LOW = "marsh energy low"
  BEAVER_STATE_MARSH_HEALTH_MED = "marsh energy med"
  BEAVER_STATE_MARSH_HEALTH_HIGH = "marsh energy high"
  BEAVER_STATE_HAS_LUMBER = "has lumber"
  BEAVER_STATE_NO_LUMBER = "no lumber"
  BEAVER_STATE_SEE_TREE = "see tree"
  BEAVER_STATE_AT_TREE = "at tree"
  BEAVER_STATE_NONE_TREE = "none tree"
  BEAVER_STATE_SEE_MARSH = "see marsh"
  BEAVER_STATE_AT_MARSH = "at marsh"
  BEAVER_STATE_NONE_MARSH = "none marsh"
  BEAVER_STATE_SEE_WOLF = "see wolf"
  BEAVER_STATE_NONE_WOLF = "none wolf"
