class GameParameters:
  BG_COLOR = (0, 92, 9)
  HEALTHBAR_COLOR = (0, 255, 0)
  HEALTHBAR_HEIGHT = 5

  SCREEN_WIDTH = 640
  SCREEN_HEIGHT = 400

  FRAMERATE = 60

class AgentParameters:
  ALPHA = 0.5
  GAMMA = 0.0
  INITIAL_ACTION_VALUE_TABLE_VALUE = 0.0

class BeaverParameters:
  CONST_VIEW_DIST = 300
  CONST_SCENT_DIST = 200
  CONST_STEP_SIZE_LAND = 1 # pixels
  CONST_STEP_SIZE_WATER = 4

  CONST_LUMBER_WEIGHT = 2

  CONST_INITIAL_ENERGY = 100
  CONST_DEAD_ENERGY_THRESHOLD = 0
  CONST_LOW_ENERGY_THRESHOLD = 30
  CONST_MED_ENERGY_THRESHOLD = 70

  CONST_ENERGY_IDLE_COST = .01
  CONST_ENERGY_WALK_LAND_COST = 0.5
  CONST_ENERGY_WALK_WATER_COST = 0.25
  CONST_ENERGY_EAT_GAIN = 0.5
  CONST_ENERGY_PICK_UP_LUMBER_COST = 0.25

class MarshParameters:
  INITIAL_HEALTH = 50
  MAX_HEALTH = 150
  MIN_HEALTH = 20

  LOW_HEALTH_THRESHOLD = 30
  MED_HEALTH_THRESHOLD = 70

  HEALTH_LUMBER_GAIN = 10
  HEALTH_IDLE_COST = 0.025

class TerrainParameters:
  MAX_NUM_TREES = 50

class TreeParameters:
  INITIAL_HEALTH = 100
  HEALTH_EATEN_COST = 1
  HEALTH_FORAGED_COST = 50

class WolfParameters:
  CONST_VIEW_DIST = 100
  CONST_SCENT_DIST = 200
  CONST_STEP_SIZE = 2